# Generated by Django 4.2.30 on 2026-08-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000)),
                ('pid', models.CharField(max_length=30)),
                ('seq', models.CharField(max_length=10000)),
                ('desc', models.CharField(max_length=500)),
                ('species', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('abstract', models.CharField(max_length=1000)),
                ('doi', models.CharField(max_length=100)),
                ('additional_details', models.CharField(default='', max_length=400)),
                ('ptm', models.CharField(default='', max_length=200)),
                ('ic50', models.FloatField(blank=True, null=True)),
                ('inhibition_type', models.TextField(blank=True, null=True)),
                ('inhibited_microorganisms', models.TextField(blank=True, null=True)),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='mbpdb_replica.function')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=10000)),
                ('pvid', models.CharField(max_length=30)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig_proteins', to='mbpdb_replica.proteininfo')),
            ],
        ),
        migrations.CreateModel(
            name='PeptideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peptide', models.CharField(max_length=500)),
                ('protein_variants', models.CharField(default='', max_length=100)),
                ('intervals', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('time_approved', models.DateTimeField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='mbpdb_replica.proteininfo')),
            ],
        ),
        migrations.AddField(
            model_name='function',
            name='pep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='mbpdb_replica.peptideinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('pep', 'function')},
        ),
    ]
