# Generated by Django 4.2.30 on 2026-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbpdb_replica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peptideinfo',
            name='peptide',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='proteininfo',
            name='pid',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
